### ISSUE TITLE
Can't view/edit any files on removable drives, in ~/snap, and any hidden files.

### ISSUE THREAD

**Issue by evanmohr** [ubuntu/gnome-text-editor#13]
I can't view any hidden files in my home folder, such as ".bashrc" or a text file I created called ".hi". I can view non-hidden files, such as a file I created called "hello".

I also can't view any files in ~/snap or on secondary drives.

**Comment by sergio-costas** [comment]
The part for "snap" and hidden files is "intentional", at least for "generic snaps". It's true that G-T-E should have an exception, so I'll check what can I do. About secondary drives, that seems to be a missing interface. I'll check it too.
