### ISSUE TITLE
Missing features and misbehaves in the snap package

### ISSUE THREAD

**Issue by soumyaDghosh** [ubuntu/gnome-text-editor#19]
The snap package lacks the option to adapt to the system preference of light/dark mode, also, on clicking any link it opens it twice in the default browser. There is also times when clicking on links many times(different or same) causes the snap to crash.

https://github.com/ubuntu/gnome-text-editor/assets/72045785/1305c2b3-4192-4191-a220-3478c6314532

**Comment by jbicha** [comment]
Please file separate bugs for each specific issue you notice instead of grouping them into a single "app is broken" issue.
