### ISSUE TITLE
Missing statusbar and some features

### ISSUE THREAD

**Issue by NicolasGoeddel** [ubuntu/gnome-text-editor#27]
Hi there,

I just installed Ubuntu 24.04 because I was not able to upgrade from Ubuntu 22.04 because some issues with the `update-manager` package.

As I needed to work with some text files I found out that `gedit` was no longer there and it was replaced with `gnome-text-editor`. I am missing three important features:
- I can no longer see in which column my cursor is
- I can no longer switch to a different syntax highlighting without opening the burger menu with multiple mouse clicks
- I can no longer switch the tab size easily

Because all of this I removed the package again and replaced it with `gedit`.
Are these missing features on your list to be added again and make it worth installing `gnome-text-editor` again?

**Comment by jbicha** [comment]
This Github project is only for the Snap packaging. gnome-text-editor provided in the default Ubuntu 24.04 LTS Desktop install is not packaged as a snap. Therefore, I'm going to close this issue.

You can report a bug against the Ubuntu .deb package by running `ubuntu-bug gnome-text-editor` . You can browse existing Ubuntu bugs at https://bugs.launchpad.net/ubuntu/+source/gnome-text-editor

The upstream project issues are at https://gitlab.gnome.org/GNOME/gnome-text-editor/-/issues

- You can click the gear button and enable Show Line Numbers to easily see what column your cursor is
- The gear button is also where you can change Document Type which will change the syntax highlighting. If you save your document, gnome-text-editor can automatically determine the document type in many cases. For instance a .md file is recognized as Markdown.
- The gear button is where you can change spaces per tab.
